Assignemt1 and Assignment 2
Ams12/JavaAssignments pull request #1
Opened 2023-03-14 13:18 UTC by Ams12

Assignment 1: Check if All Characters Have Equal Number of Occurrences
Assignment 2: Find Destination City

2023-03-23 12:11 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/PrimitiveDataTypes.java
> +
Remove the extra space.

2023-03-23 12:12 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/PrimitiveDataTypes.java
> +		byte b = 2;
Give proper understandable name to variable.

2023-03-23 12:13 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/NonPrimitiveDataTypes.java
> +		//System.out.println(arr); // prints the whole memory location value
don't push not required commented code.

2023-03-23 12:13 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/ImplicitDataTypeConversion.java
> +
Write the question before writing the program in commented format.

2023-03-23 12:14 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/ImplicitDataTypeConversion.java
> +		int a = 100;
Use method to write the repeatable code.

2023-03-23 12:14 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/PrimitiveDataTypes.java
> +
Use the comments for all the programs.

2023-03-23 12:42 UTC, amitsahu8 requested changes

2023-03-23 12:42 UTC, amitsahu8 commented on src/com/encora/javaAssignments/GoodString.java
> +      boolean isGoodString = true;
default boolean should be false and check of true condition

2023-03-23 12:42 UTC, amitsahu8 commented on src/com/encora/javaAssignments/GoodString.java
> +      String s = "abacbdc";
use meaningful variable name

2023-03-23 12:42 UTC, amitsahu8 commented on src/com/encora/javaAssignments/DestinationCity.java
> +		if (input.length == 1) {
try without any datatype in hashmap

2023-03-27 07:14 UTC, rohitlamsonge66 approved these changes

2023-03-27 07:14 UTC, merged