Checkin all programs again
Ams12/JavaAssignments pull request #4
Opened 2023-03-27 08:33 UTC by Ams12

2023-03-27 10:58 UTC, amitsahu8 requested changes

2023-03-27 10:58 UTC, amitsahu8 commented on src/com/encora/javaAssignments/ArraysInJava.java
> +        int[] arr = {11,22,33,44,55};
please follow the points mentioned in teams

2023-03-29 06:12 UTC, amitsahu8 requested changes

2023-03-29 06:12 UTC, amitsahu8 commented on src/com/encora/javaAssignments/GoodString.java
> +        for (Object value : charCount.values()) {
No need of Object here, you can use Integer

2023-03-29 06:12 UTC, amitsahu8 commented on src/com/encora/javaAssignments/GoodString.java
> +                result = 0;
instead of break you can return false

2023-03-29 06:12 UTC, amitsahu8 commented on src/com/encora/javaAssignments/GoodString.java
> +        String stringName = "jjvva";
move the core code to new method and use it in main

2023-03-29 08:45 UTC, prashantkawa requested changes

2023-03-29 08:45 UTC, prashantkawa commented on src/com/encora/javaAssignments/ImplicitDataTypeConversion.java
> +        float city = name;
Try giving meaningful name to variables

2023-03-29 10:11 UTC, prashantkawa requested changes
Try creating method for logic and then call that method from main method

2023-03-29 10:11 UTC, prashantkawa commented on src/com/encora/javaAssignments/DestinationCity.java
> +        String[][] input = {{"B", "C"}, {"D", "B"}, {"C", "A"}};
Array name should be proper

2023-03-29 10:11 UTC, prashantkawa commented on src/com/encora/javaAssignments/DestinationCity.java
> +        //String[][] input = {{"A","Z"}};
Remove commented code

2023-03-29 10:11 UTC, prashantkawa commented on src/com/encora/javaAssignments/ExplicitDataTypeConversion.java
> +        System.out.println("Integer representation: " + integerNumber);
Create method for logic

2023-03-29 10:11 UTC, prashantkawa commented on src/com/encora/javaAssignments/FindLengthOfArray.java
> +        int[] lengthOfArray = new int[6];
Again array name should be proper

2023-03-29 10:30 UTC, amitsahu8 approved these changes

2023-03-30 03:04 UTC, prashantkawa requested changes

2023-03-30 03:04 UTC, prashantkawa commented on src/com/encora/javaAssignments/GoodString.java
> +
what is the use of this

2023-03-30 03:04 UTC, prashantkawa commented on src/com/encora/javaAssignments/GoodString.java
> +        boolean isGoodString = false;
Same here just created variable not using it

2023-03-30 06:39 UTC, prashantkawa approved these changes
Approving PR

2023-03-30 06:42 UTC, merged