Control Flow Statements
Ams12/JavaAssignments pull request #6
Opened 2023-03-31 13:13 UTC by Ams12

2023-04-03 03:27 UTC, prashantkawa approved these changes
Approving PR

2023-04-03 05:33 UTC, amitsahu8 requested changes

2023-04-03 05:33 UTC, amitsahu8 commented on src/com/encora/javaAssignments/ControlFlowStatements/IfElseIfStatement.java
> +
please follow the coding guideline points, go through it properly

2023-04-03 05:33 UTC, amitsahu8 commented on src/com/encora/javaAssignments/ControlFlowStatements/IfElseStatement.java
> +package ControlFlowStatements;
above same comment for all the files

2023-04-04 03:33 UTC, prashantkawa requested changes

2023-04-04 03:33 UTC, prashantkawa commented on src/com/encora/javaAssignments/ControlFlowStatements/IfStatement.java
> +    }
For negative input both the statements will get printed, please change the logic

2023-04-04 03:33 UTC, prashantkawa commented on src/com/encora/javaAssignments/ControlFlowStatements/NestedIfDemo.java
> +        // int integerNumber = 50;
remove commented code

2023-04-04 08:20 UTC, amitsahu8 approved these changes

2023-04-04 08:20 UTC, merged