Medium complexity assignment 1 - Employee Tax
Ams12/JavaAssignments pull request #8
Opened 2023-04-05 16:04 UTC by Ams12

2023-04-06 02:05 UTC, amitsahu8 requested changes

2023-04-06 02:05 UTC, amitsahu8 commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTax.java
> +        if (income <= 700000) {
use switch case

2023-04-06 04:00 UTC, prashantkawa requested changes

2023-04-06 04:00 UTC, prashantkawa commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTax.java
> +        }
Try writing logic in method and call that method from main method

2023-04-07 08:49 UTC, prashantkawa requested changes

2023-04-07 08:49 UTC, prashantkawa commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTaxUsingSwitchCase.java
> +        taxSlab = (salary > 700000 && salary <= 1000000) ? 2 : (salary > 1000000 && salary <= 1500000) ? 3 : (salary > 1500000) ? 4 : 1;
please verify the conditions again and change it accordingly

2023-04-07 08:49 UTC, prashantkawa commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTaxUsingSwitchCase.java
> +                System.out.println("taxFor30Percent: " + taxFor30Percent);
just print total tax amount

2023-04-07 11:02 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTax.java
> +
remove extra spaces

2023-04-07 11:03 UTC, rohitlamsonge66 commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/employeeTax.README.md
> +Result: - income tax is ……………………………. 
add output in read me.

2023-04-10 03:20 UTC, prashantkawa approved these changes
Approving PR

2023-04-10 05:55 UTC, amitsahu8 requested changes

2023-04-10 05:55 UTC, amitsahu8 commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTax.java
> +        taxSlab = (salary <= 700000) ? 1 : (salary > 700000 && salary <= 1000000) ? 2 : (salary > 1000000 && salary <= 1500000) ? 3 : 4;        System.out.println("taxSlab: " + taxSlab);
sout should be in new line

2023-04-10 05:55 UTC, amitsahu8 commented on src/com/encora/javaAssignments/MediumComplexityProblems/employeeTax/EmployeeTax.java
> +public class EmployeeTax {
space missing between package and method

2023-04-10 06:04 UTC, amitsahu8 approved these changes

2023-04-10 06:04 UTC, merged