Swap array element if Prime
Ams12/JavaAssignments pull request #9
Opened 2023-04-10 11:21 UTC by Ams12

2023-04-10 11:53 UTC, prashantkawa requested changes

2023-04-10 11:53 UTC, prashantkawa commented on src/com/encora/javaAssignments/MediumComplexityProblems/swappingArrayElement/swappingArrayElementREADME.md
> +Swapped array is: [3, 2, 1]
This inputs are not given in code

2023-04-10 11:53 UTC, prashantkawa commented on src/com/encora/javaAssignments/MediumComplexityProblems/swappingArrayElement/swappingArrayElementREADME.md
> +
Not used

2023-04-10 11:53 UTC, prashantkawa commented on src/com/encora/javaAssignments/MediumComplexityProblems/swappingArrayElement/SwappingArrayElement.java
> +    }
This condition will fail for last element as 4

2023-04-11 05:42 UTC, amitsahu8 requested changes

2023-04-11 05:42 UTC, amitsahu8 commented on src/com/encora/javaAssignments/MediumComplexityProblems/swappingArrayElement/SwappingArrayElement.java
> +        for (index = 2; index <= number / 2; index++) {
return true in if condition when number is prime

2023-04-11 08:00 UTC, amitsahu8 approved these changes

2023-04-11 08:04 UTC, prashantkawa approved these changes
Approving PR

2023-04-11 08:16 UTC, merged